[sinks.humio]
  # General
  type = "humio_logs"
  inputs = ["log_json"]
  compression = "gzip"
  host_key = "fly.app.instance"
  endpoint = "https://cloud.community.humio.com"
  token = "${HUMIO_TOKEN}"

  # Encoding
  encoding.codec = "json"

